<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251204211059 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, tier_list_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_249E978AB25FD8A1 ON tier (tier_list_id)');
        $this->addSql('CREATE TABLE tier_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4498D717E3C61F9 ON tier_list (owner_id)');
        $this->addSql('CREATE TABLE tieritem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, image VARCHAR(255) NOT NULL, position INT NOT NULL, tier_id INT DEFAULT NULL, tier_list_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6629E71A354F9DC ON tieritem (tier_id)');
        $this->addSql('CREATE INDEX IDX_B6629E71B25FD8A1 ON tieritem (tier_list_id)');
        $this->addSql('ALTER TABLE tier ADD CONSTRAINT FK_249E978AB25FD8A1 FOREIGN KEY (tier_list_id) REFERENCES tier_list (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tier_list ADD CONSTRAINT FK_C4498D717E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tieritem ADD CONSTRAINT FK_B6629E71A354F9DC FOREIGN KEY (tier_id) REFERENCES tier (id)');
        $this->addSql('ALTER TABLE tieritem ADD CONSTRAINT FK_B6629E71B25FD8A1 FOREIGN KEY (tier_list_id) REFERENCES tier_list (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tier DROP CONSTRAINT FK_249E978AB25FD8A1');
        $this->addSql('ALTER TABLE tier_list DROP CONSTRAINT FK_C4498D717E3C61F9');
        $this->addSql('ALTER TABLE tieritem DROP CONSTRAINT FK_B6629E71A354F9DC');
        $this->addSql('ALTER TABLE tieritem DROP CONSTRAINT FK_B6629E71B25FD8A1');
        $this->addSql('DROP TABLE tier');
        $this->addSql('DROP TABLE tier_list');
        $this->addSql('DROP TABLE tieritem');
    }
}
